<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Unload.ProjectSync</RootNamespace>
    <AssemblyName>Unload.ProjectSync</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Update="project-sync.example.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
