<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Unload.Bootstrapper\Unload.Bootstrapper.csproj" />
    <ProjectReference Include="..\Unload.Gateway\Unload.Gateway.csproj" />
    <ProjectReference Include="..\Unload.Store\Unload.Store.csproj" />
    <ProjectReference Include="..\Unload.Tasks\Unload.Tasks.csproj" />
    <ProjectReference Include="..\Unload.Tasks.ExtraUnload\Unload.Tasks.ExtraUnload.csproj" />
    <ProjectReference Include="..\Unload.Tasks.MainUnload\Unload.Tasks.MainUnload.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="NLog.Web.AspNetCore">
      <Version>6.1.2</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
