<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Unload.Bootstrapper\Unload.Bootstrapper.csproj" />
    <ProjectReference Include="..\Unload.Gateway\Unload.Gateway.csproj" />
    <ProjectReference Include="..\Unload.Store\Unload.Store.csproj" />
    <ProjectReference Include="..\Unload.Tasks\Unload.Tasks.csproj" />
    <ProjectReference Include="..\Unload.Tasks.ExtraUnload\Unload.Tasks.ExtraUnload.csproj" />
    <ProjectReference Include="..\Unload.Tasks.MainUnload\Unload.Tasks.MainUnload.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="NLog.Web.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
