<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Unload.Bootstrapper\Unload.Bootstrapper.csproj" />
    <ProjectReference Include="..\Unload.Run.Application\Unload.Run.Application.csproj" />
    <ProjectReference Include="..\Unload.Store\Unload.Store.csproj" />
    <ProjectReference Include="..\Unload.TaskFlow\Unload.TaskFlow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Web.AspNetCore">
      <Version>6.1.2</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
